import fs from 'node:fs';
import path from 'node:path';
export function writeReport(store, config) {
  const state = store.state;
  const report = { label: 'Agents simulant une démarche de QA humain — noyau expérimental', id: config.id, calls: state.calls, reservedMicros: state.reservedMicros, holds: state.holds.length, intents: Object.values(state.intents), coverage: state.coverage, hypotheses: state.candidates, observations: state.observations.map(o=>({id:o.id,path:o.path,screenshot:o.screenshot,errors:o.errors,overflow:o.overflow})), limits: ['Un verdict métier vaut seulement pour les checks et le périmètre des probes configurés.', 'Aucune certification exhaustive, de paie ou de sécurité serveur.', 'Hypothèses du modèle non confirmées : revue indépendante requise.', 'Captures privées ; masquage des secrets connus ne garantit pas anonymisation de toutes données.'] };
  report.workers=state.workerUsage || {};
  report.actions=Object.entries(state.steps).map(([id,step])=>({id,...step}));
  report.providerFault=state.providerFault || null;
  report.costMeaning=Object.values(report.workers).some(w=>w.billingMode==='subscription')?'Subscription CLI: reported USD cost is unavailable; zero reservation is not a zero-cost invoice.':'Persistent maximum reservations; not a supplier invoice.';
  fs.writeFileSync(path.join(store.directory,'report.json'),JSON.stringify(report,null,2));
  const line = value => String(value ?? '').replace(/[\r\n|]/g,' ');
  const candidates = report.hypotheses.map(c=>c.kind==='deterministic-failure'?`- Contrôle ${line(c.check)} : attendu ${line(JSON.stringify(c.expected))} ; observé ${line(JSON.stringify(c.observed[0]?.checks))}. Impact : ${line(c.impact)}. Reproduction : scénario ${line(c.scenario)}, puis deux lectures de contrôle ; preuve UI ${c.evidence}. Portée et revue : ${line(c.qualification)}.`:`- Proposition non confirmée : ${line(c.claim || JSON.stringify(c.finding))}. Preuve UI ${c.evidence}. Impact à revoir indépendamment.`).join('\n');
  const markdown = `# Rapport QA — ${line(config.id)}\n\n${report.label}\n\n${report.calls} appels ; réservation ${report.reservedMicros} micro-USD ; ${report.holds} intention(s) non rapprochée(s).\n\n| Scénario | Observé par le moteur | Reproduction | Preuve indépendante |\n|---|---|---|---|\n` + report.intents.map(i=>`| ${line(i.scenario)} | ${i.phase} | configuration scénario ${line(i.scenario)}, étape ${line(i.step)} ; ne pas resoumettre | ${i.evidence.filter(e=>e.matched).map(e=>e.id).join(', ') || 'aucune preuve concluante'} |`).join('\n') + '\n\n## Contrôles\n\n' + report.coverage.map(c=>`- ${line(c.scenario)} / ${line(c.check)} : ${c.verdict} (${c.evidence.join(', ')})`).join('\n') + '\n\n## Observations, hypothèses et impact\n\n' + (candidates || 'Aucune hypothèse modèle.') + '\n\n' + report.limits.map(l=>`- ${l}`).join('\n') + '\n\nLes valeurs attendues/observées, scopes (unité/date/fuseau/compte) et preuves sont dans report.json. Les images observation-*.png sont locales et privées. Une absence de requête ou HTTP 200 ne prouve aucun succès métier.\n';
  fs.writeFileSync(path.join(store.directory,'REPORT.md'),markdown+`\nCoûts : ${report.costMeaning}\n\nAgents exécutants : ${Object.entries(report.workers).map(([id,w])=>`${id}: ${w.calls} appel(s), ${w.reportedTokens || 0} tokens rapportés, ${w.billingMode}`).join(' ; ') || 'aucun appel modèle'}.\n`);
  return report;
}
